# [package]
# name = "zodak"
# version = "0.1.0"
# authors = ["Rob Saunders <rob@wearebrandnew.com>"]

# [dependencies]
# byteorder = "1.1"
# docopt = "0.8"

# [[bin]]
# name = "zodak"
# doc = false

# [lib]
# doc = false

[workspace]
members = ["zodak", "wavtag"]
