[package]
name = "zodak"
version = "0.1.1"
authors = ["Monomadic <themonomadic@protonmail.com>"]
edition = "2021"

[dependencies]
docopt = "1.1"
wavtag = { path = "../wavtag" }
regex = "1.10"

[[bin]]
name = "zodak"
doc = false
