[package]
name = "zodak"
version = "0.1.1"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
docopt = "1.1"
wavtag = { path = "../wavtag" }
regex = "1.10"

[[bin]]
name = "zodak"
doc = false
